# Generated by Django 3.1.7 on 2026-07-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0038_auto_20260430_0111"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityAlert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Internal identifier, not shown to users.",
                        max_length=256,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Alert content as markdown. Supports hyperlinks."
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=64,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exclude_communities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Hidden from these communities.",
                        related_name="community_alert_exclusions",
                        to="community.Community",
                    ),
                ),
                (
                    "require_communities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Shown only in these communities. If empty, shown everywhere.",
                        related_name="community_alert_inclusions",
                        to="community.Community",
                    ),
                ),
            ],
            options={
                "ordering": ("-ordering", "-pk"),
            },
        ),
    ]
