name: Trigger deploy

on:
  push:
    tags:
      - "*.*.*"

jobs:
  deploy:
    name: Trigger deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    steps:
      - name: Call deployment workflow
        run: |
          curl \
            -X POST \
            -u "${{ secrets.DEPLOY_WORKFLOW_DISPATCH_USER }}:${{ secrets.DEPLOY_WORKFLOW_DISPATCH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            ${{ secrets.DEPLOY_WORKFLOW_DISPATCH_URL }} \
            -d '{"ref": "master", "inputs": {"tag": "${{ github.ref_name }}"}}'
